version: '3.3'
services:
  redis:
    image: redis:4.0-alpine
    container_name: redis-storage
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redisdata:/data
  mongo:
    image: mongo:latest
    container_name: mongo-storage
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - ./data:/data
    ports:
      - "27017:27017"
    restart: always

volumes:
  redisdata:
    driver: "local"
