version: '3.3'
services:
  redis:
    image: redis:4.0-alpine
    container_name: redis-storage
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redisdata:/data
  mongo-v1:
    image: bitnami/mongodb:4.4.1-debian-10-r39
    container_name: mongo-storage-v1
    ports:
      - "27017:27017"
    restart: always

  mongo-v2:
    image: bitnami/mongodb:5.0.9-debian-10-r0
    container_name: mongo-storage-v2
    ports:
      - "27018:27017"
    restart: always

  mongo-v2-frontier:
    image: bitnami/mongodb:7.0.4-debian-11-r0
    container_name: mongo-storage-frontier
    ports:
      - "27019:27017"
    restart: always

volumes:
  redisdata:
    driver: "local"
